AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Main API Gateway and Lambda modules with shared REST API

Globals:
  Function:
    Runtime: python3.9
    Timeout: 10
    MemorySize: 256

Parameters:
  StageName:
    Type: String
    Default: prod
    Description: API Gateway stage name

Resources:
  MainApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: MainApiGateway
      StageName: !Ref StageName
      EndpointConfiguration: REGIONAL

  UsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: project-users
      CodeUri: modules/users/
      Handler: app.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Health:
          Type: Api
          Properties:
            RestApiId: !Ref MainApi
            Path: /_health/users
            Method: GET

  OrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: project-orders
      CodeUri: modules/orders/
      Handler: app.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Health:
          Type: Api
          Properties:
            RestApiId: !Ref MainApi
            Path: /_health/orders
            Method: GET

Outputs:
  MainApiId:
    Description: Rest API ID of the shared API Gateway
    Value: !Ref MainApi
  MainApiUrl:
    Description: Base invoke URL for the shared API Gateway
    Value: !Sub https://${MainApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/


